cc_library(
    name = "autorecon",
    srcs = [
        "bundle_adjust.cc",
        "clbfile.cpp",
        "recon_geometry.cc",
        "recon_globals.cc",
    ],
    hdrs = [
        "bundle_adjust.h",
        "clbfile.h",
        "feature.h",
        "recon_geometry.h",
        "recon_globals.h",
    ],
    visibility = ["//visibility:public"],
)
