load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
  
http_archive(
   name = "my_ssl",
   urls = ["http://example.com/openssl.zip"],
   sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
   build_file = "@//:openssl.BUILD",
)

http_archive(
    name = "bazel_pkg_config",
    strip_prefix = "bazel_pkg_config-master",
    urls = ["https://github.com/cherrry/bazel_pkg_config/archive/master.zip"],
)

load("@bazel_pkg_config//:pkg_config.bzl", "pkg_config")

pkg_config(
    name = "freetype2",
)

pkg_config(
    name = "nimage",
)

pkg_config(
    name = "nmath",
)